name: Build and Push to Docker Hub

on: push

jobs:
  build-container:
    name: Clone Telegram Team/Shared Drive
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: jodiekurnia/CloneBot_Heroku
          tags: latest, ${{ github.run_number }}